### ISSUE TITLE
Saving an image from file

### ISSUE THREAD

**Issue by rossanthony** [benallfree/laravel-stapler-images#1]
Is it possible to use Stapler's method for saving images uploaded as files? So something like:

```
// Upload an image
$user->avatar = Input::file('avatar');
$user->save();
```

Rather than using from_url method as shown in your example...

```
// Create an image
$url = "http://www.gravatar.com/avatar/71137e6e1c94b72f162da3262b700017.png";
$user->avatar = Image::from_url($url);
$user->save();
```

**Comment by benallfree** [comment]
I think that will work. Have you tried it?

**Comment by rossanthony** [comment]
Yep, tried it but no luck. 

Can I ask why the URL field is necessary? When using laravel-stapler, it seems that if adding a new image from a url it will take a copy of the image and save it locally (updating the img_file_name, img_file_size, img_content_type, img_updated_at fields in the corresponding model table), rather than reference the URL of the remote file.

Also with regards to the way relationships are handled, I understand that it's necessary to add an {image_type}_id field to the table of each model which has an image. So in your example the Users table would need an avatar_id field which would link it to the id column in the Images table.

The project I'm working on requires that some of the models have multiple images (of different types/sizes), therefore I'm thinking that a polymorphic relationship will work better in this case. Otherwise I will need multiple {image_type}_id fields in each model table.

**Comment by benallfree** [comment]
Here is an example of fetching from a file. If you wanted to make a `from_file` helper method in the `Image` class, that would be great :)

```
    $file = Input::file('image');
    if(!is_a($file, 'Symfony\Component\HttpFoundation\File\UploadedFile'))
    {
      throw new Exception('Please upload an image file before continuing.');
    } else {
      try
      {
        $image = new Image();
        $image->image = $file;
        $image->save();
      } catch (Exception $e)
      {
        throw new Exception('We were unable to recognize that image file format. Please try uploading a different file.');
      }
    }
```

**Comment by benallfree** [comment]
To your other question about the `url` field in the table... I would actually have named that something else if I had been thinking ahead. The idea is to give some clue as to the origin or original name of the file.
