### ISSUE TITLE
ImageReprocess using Image->image instead of Image->att

### ISSUE THREAD

**Issue by nrotstan** [benallfree/laravel-stapler-images#5]
Anytime I tried to run php artisan image:reprocess, I always received an error "Call to a member function url() on null". ImageReprocess.php is loading Image::all() and then trying to reference 'image' on each one, but it looks like Image.php refers to its attachment as 'att'. Changing all $i->image references to $i->att in ImageReprocess.php fixed the problem for me.

**Comment by benallfree** [comment]
Fixed in master
